# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'BeautyMNL-MacNoble-Search' do
  use_frameworks!

  pod 'RealmSwift', '~>10'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

end